#! /bin/sh

sxhkd &

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        7
bspc config window_gap          17

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "$color8"
bspc config active_border_color "$color8"
bspc config focused_border_color "$color4"
bspc config presel_feedback_color "$color8"

compton
xrdb ~/.Xresources
feh --bg-fill ~/Pictures/Wallpapers/wallhaven-0j6r1p_1920x1080.png
