#! /bin/sh

#-----------------------------------------------------------
#                                                 _        #
#  _   _ ___  ___ _ __ _ __   __ _ _ __ ___   ___( )___    #
# | | | / __|/ _ \ '__| '_ \ / _` | '_ ` _ \ / _ \// __|   #
# | |_| \__ \  __/ |  | | | | (_| | | | | | |  __/ \__ \   #
#  \__,_|___/\___|_|  |_| |_|\__,_|_| |_| |_|\___| |___/   #
#                                                          #
#  _                                                       #
# | |__  ___ _ ____      ___ __ ___                        #
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \                       #
# | |_) \__ \ |_) \ V  V /| | | | | |                      #
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|                      #
#           |_|                                            #
#----------------------------------------------------------#


sxhkd &                                        # sxhkd, my keybinding daemon
                                               # see ~/.config/sxhkd/sxhkdrc for
                                               # my configuration

. "${HOME}/.cache/wal/colors.sh"               # Colors

bspc monitor -d I II III IV V VI VII VIII IX X # Monitors

# Basic config

bspc config border_width        6
bspc config window_gap          17

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Emacs state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# View the .cache/wal/colors.sh provided with this my dots or run M-x theme-magic-from-emacs with wal installed to get these colors

bspc config normal_border_color "$color8"
bspc config active_border_color "$color8"
bspc config focused_border_color "$color4" 
bspc config presel_feedback_color "$color8"


# Autostart

feh --bg-fill ~/Wallpapers/wallhaven-0j6r1p_1920x1080.png &
compton & 
xrdb ~/.Xresources & 
